# Generated by Django 5.0.4 on 2026-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SummaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("novice", "Novice"),
                            ("pro", "Pro"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "source_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("srt_text", models.TextField(blank=True, default="")),
                ("result_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
