# Generated by Django 6.0.1 on 2026-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryrecord',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='summaryrecord',
            name='result_json',
        ),
        migrations.RemoveField(
            model_name='summaryrecord',
            name='srt_text',
        ),
        migrations.AddField(
            model_name='summaryrecord',
            name='arguments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='summaryrecord',
            name='entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='summaryrecord',
            name='investment_takeaways',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='summaryrecord',
            name='model',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summaryrecord',
            name='one_sentence_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='summaryrecord',
            name='outlook_calls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='summaryrecord',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='summaryrecord',
            name='mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='summaryrecord',
            name='source_filename',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='summaryrecord',
            table='summaries_summaryrecord',
        ),
    ]
