# Generated by Django 5.0.4 on 2026-04-30 22:54
# Manually trimmed: only create TickerMap and BacktestingCall (other fields already exist in DB)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0002_normalize_tables"),
        ("summaries", "0003_remove_model_add_episode_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="TickerMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_name", models.CharField(max_length=50, unique=True)),
                ("ticker", models.CharField(max_length=20)),
                ("exchange", models.CharField(blank=True, max_length=10)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "ticker_map", "app_label": "summaries"},
        ),
        migrations.CreateModel(
            name="BacktestingCall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset", models.CharField(max_length=100)),
                ("ticker", models.CharField(blank=True, max_length=20)),
                ("direction", models.CharField(max_length=10)),
                ("timeframe_raw", models.CharField(max_length=50)),
                ("thesis", models.TextField(blank=True)),
                ("evidence_quote", models.TextField(blank=True)),
                ("target_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("start_time", models.DateField(blank=True, null=True)),
                ("end_time", models.DateField(blank=True, null=True)),
                ("start_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("end_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("result", models.CharField(
                    choices=[("pending", "Pending"), ("pass", "Pass"), ("fail", "Fail"), ("skip", "Skip")],
                    default="pending", max_length=10,
                )),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("episode", models.ForeignKey(
                    blank=True, db_constraint=False, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="backtesting_calls",
                    to="podcasts.podcastepisode",
                )),
                ("summary", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="backtesting_calls",
                    to="summaries.summaryrecord",
                )),
            ],
            options={
                "db_table": "backtesting_call",
                "app_label": "summaries",
                "indexes": [
                    models.Index(fields=["result", "end_time"], name="backtesting_result_9a85f5_idx"),
                    models.Index(fields=["ticker", "start_time"], name="backtesting_ticker_523cee_idx"),
                ],
            },
        ),
    ]
