# Generated by Django 5.0.4 on 2026-04-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0002_normalize_tables"),
        ("summaries", "0004_add_tickermap_backtestingcall"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summaryrecord",
            name="outlook_calls",
        ),
        migrations.AddField(
            model_name="summaryrecord",
            name="glossary_matches",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="summaryrecord",
            name="mind_map",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="summaryrecord",
            name="podcaster",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="summaryrecord",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BacktestingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(default="", max_length=100)),
                ("ticker", models.CharField(blank=True, default="", max_length=20)),
                ("direction", models.CharField(default="", max_length=10)),
                ("timeframe_raw", models.CharField(default="", max_length=50)),
                ("thesis", models.TextField(blank=True, default="")),
                ("evidence_quote", models.TextField(blank=True, default="")),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("start_time", models.DateField(blank=True, null=True)),
                ("end_time", models.DateField(blank=True, null=True)),
                (
                    "start_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "end_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("skip", "Skip"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backtesting_records",
                        to="podcasts.podcastepisode",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        db_column="summary_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtesting_records",
                        to="summaries.summaryrecord",
                    ),
                ),
            ],
            options={
                "db_table": "backtesting",
            },
        ),
        migrations.DeleteModel(
            name="BacktestingCall",
        ),
    ]
