# Generated by Django 6.0.1 on 2026-07-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_normalize_tables'),
        ('summaries', '0004_speakeraccuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSentimentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=20)),
                ('base', models.FloatField(blank=True, null=True)),
                ('annual_vol', models.FloatField(blank=True, null=True)),
                ('macro_score', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_sentiment_scores', to='podcasts.podcastepisode')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sentiment_scores', to='summaries.summaryrecord')),
            ],
            options={
                'db_table': 'stock_sentiment_score',
                'unique_together': {('summary', 'asset_name')},
            },
        ),
    ]
