# Generated by Django 5.0.4 on 2026-07-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0005_stocksentimentscore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backtestingrecord",
            name="call_risk",
        ),
        migrations.RemoveField(
            model_name="summaryrecord",
            name="episode_macro",
        ),
        migrations.RemoveField(
            model_name="summaryrecord",
            name="episode_risk",
        ),
    ]
