# Generated by Django 5.0.4 on 2026-08-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0006_remove_backtestingrecord_call_risk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestingrecord",
            name="evidence_timestamps",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
