# Generated by Django 5.0.4 on 2026-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0008_drop_reintroduced_ghost_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialReportCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("fiscal_period_end", models.DateField()),
                ("data_source", models.CharField(max_length=20)),
                ("revenue", models.FloatField(blank=True, null=True)),
                ("gross_profit", models.FloatField(blank=True, null=True)),
                ("operating_income", models.FloatField(blank=True, null=True)),
                ("ebit", models.FloatField(blank=True, null=True)),
                ("net_income", models.FloatField(blank=True, null=True)),
                ("shares_outstanding", models.FloatField(blank=True, null=True)),
                ("eps", models.FloatField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "financial_report_cache",
                "unique_together": {("ticker", "fiscal_period_end")},
            },
        ),
    ]
