# Generated by Django 5.0.4 on 2026-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0009_financialreportcache"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialreportcache",
            name="disclosure_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
