# Generated by Django 5.0.4 on 2026-09-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0010_financialreportcache_disclosure_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20, unique=True)),
                ("market", models.CharField(blank=True, max_length=10)),
                ("industry_code", models.CharField(blank=True, max_length=10)),
                ("industry_name", models.CharField(blank=True, max_length=50)),
                ("sector_name", models.CharField(blank=True, max_length=50)),
                ("source", models.CharField(blank=True, max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "industry_classification",
            },
        ),
    ]
