# Generated by Django 5.0.4 on 2026-08-15 18:39, hand-edited
#
# makemigrations 只產生了 AlterModelOptions（因為 UserProfile 在 migration state
# 裡本來就「已存在」——0001_initial 的 CreateModel 因為 managed=False 從沒真的建過
# 表）。改成 managed=True 之後，state 層面的 options 有更新，但單獨 AlterModelOptions
# 不會補發任何 DDL，所以這裡用 SeparateDatabaseAndState 額外補一個「只在資料庫層面
# 真的建表、不動 migration state」的 CreateModel，state 已經是對的、不用重複註冊。

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.CreateModel(
                    name='UserProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('user_id', models.IntegerField(unique=True)),
                        ('level', models.CharField(blank=True, max_length=20)),
                        ('markets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                        ('style', models.CharField(blank=True, max_length=20)),
                        ('goal', models.CharField(blank=True, max_length=20)),
                        ('capital', models.CharField(blank=True, max_length=10)),
                        ('onboarding_done', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'user_profile',
                    },
                ),
            ],
            state_operations=[],
        ),
    ]
