# Generated by Django 6.0.1 on 2026-03-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=255, verbose_name='頻道名稱')),
                ('episode_title', models.CharField(max_length=255, verbose_name='單集標題')),
                ('audio_url', models.URLField(max_length=500, verbose_name='音檔連結')),
                ('srt_content', models.TextField(verbose_name='校對後繁體逐字稿')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'podcasts_metadata',
            },
        ),
    ]
