# Generated by Django 6.0.1 on 2026-02-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('short_definition', models.TextField()),
                ('long_definition', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('lang', models.CharField(default='zh-TW', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='glossary.glossaryterm')),
            ],
            options={
                'indexes': [models.Index(fields=['alias'], name='glossary_gl_alias_99b220_idx')],
            },
        ),
    ]
