# Generated by Django 6.0.1 on 2026-02-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='glossaryalias',
            constraint=models.UniqueConstraint(fields=('term', 'alias'), name='uniq_term_alias'),
        ),
    ]
