# Generated by Django 6.0.1 on 2026-03-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraphLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('target', models.TextField()),
                ('relation_type', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('summary_date', models.DateField(null=True)),
                ('podcast_source', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphNode',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('industry', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'nodes',
                'managed': False,
            },
        ),
    ]
