# Generated by Django 5.0.4 on 2026-08-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_graph", "0002_financialmetricscache"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialmetricscache",
            name="price_at_period_end",
            field=models.FloatField(null=True),
        ),
    ]
