from django.urls import path
from . import views

urlpatterns = [
    path("graph/",                    views.graph_page),
    path("graph-diff/",               views.graph_diff_page),
    path("claim-analysis/",           views.claim_analysis_page),
    path("latest-date/",              views.latest_date_api),
    path("hot-nodes/",                views.hot_nodes_api),
    path("node-episodes/",            views.node_episodes_api),
    path("graph-data/",               views.graph_data_api),
    path("graph-diff-data/",          views.graph_diff_api),
    path("graph-diff-narrative/",     views.graph_diff_narrative_api),
    path("industries/",               views.industries_api),
    path("graph-narrative/",          views.graph_narrative_api),
    path("episodes/",                 views.episodes_api),
    path("analyze-episode/",          views.analyze_episode_api),
    path("generate/",                 views.generate_graph),
    path("generate-from-summaries/",  views.generate_graph_from_summaries),
    path("generate-narrative/",       views.generate_narrative_graph),
    path("narrative-cluster/",            views.narrative_cluster_page),
    path("narrative-cluster-data/",       views.narrative_cluster_api),
    path("narrative-cluster-diff/",       views.narrative_cluster_diff_page),
    path("narrative-cluster-diff-data/",  views.narrative_cluster_diff_api),
    path("leiden-cluster/",               views.leiden_cluster_page),
    path("leiden-cluster-data/",          views.leiden_cluster_api),
    path("name-clusters/",                views.name_clusters_api),
    path("basket/",                       views.basket_page),
    path("basket-data/",                  views.basket_api),
    path("basket-purposes/",              views.basket_purposes_api),
]
